from __future__ import annotations

import struct

PROTOCOL_MAGIC = b"XERO"
CURRENT_PROTOCOL_VERSION = 1
KEY_EXCHANGE_ALGORITHM = "X25519-HKDF-SHA256"
PAYLOAD_ENCRYPTION_ALGORITHM = "AES-256-GCM"
INTEGRITY_ALGORITHM = "HMAC-SHA256"

FRAME_HEADER = struct.Struct("!4sBBBBI16s12s32s")
FRAME_HEADER_LENGTH = FRAME_HEADER.size
FRAME_HMAC_LENGTH = 32
AES_GCM_TAG_LENGTH = 16

HKDF_INFO = b"xero-protocol-v1"
